name: Deploy Backend to AWS Lambda

on:
  push:
    branches: [main]
    paths: ['Backend/**']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Serverless Framework
      run: npm install -g serverless
      
    - name: Install Serverless Plugins
      working-directory: ./Backend
      run: |
        npm init -y
        npm install serverless-python-requirements
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Deploy to AWS
      working-directory: ./Backend
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: serverless deploy --stage prod
